services:
  - type: web
    name: sazug-srms
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: 'your_mysql_host_here'
      - key: DB_NAME
        value: 'sazug_srms'
      - key: DB_USER
        value: 'root'
      - key: DB_PASS
        value: ''
      - key: APP_ENV
        value: 'production'
      - key: SESSION_SECURE
        value: 'true'