services:
  - type: web
    name: sazug-srms
    runtime: php
    buildCommand: |
      if [ ! -f vendor/autoload.php ]; then
        composer install --no-dev --optimize-autoloader
      fi
    startCommand: apachectl -D FOREGROUND
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
